services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: calorie_db
    command: --default-authentication-plugin=mysql_native_password --default-time-zone='+07:00'
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Ho_Chi_Minh

    ports:
      # Map port từ file .env (3307) vào port trong docker (3306)
      - "${DB_PORT}:3306"

    volumes:
      # QUAN TRỌNG 1: Nạp file .sql (cấu trúc + data) vào để tự chạy lần đầu
      - ./db_init:/docker-entrypoint-initdb.d

      # QUAN TRỌNG 2: Giữ lại dữ liệu kể cả khi tắt container
      - mysql_data:/var/lib/mysql

# Khai báo volume để lưu data
volumes:
  mysql_data:
